server:
  port: 8080
spring:
  kafka:
    admin:
      client-id: kafka-admin
      properties:
        bootstrap.servers: localhost:9092
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: account-service-group
      properties:
        spring.json.trusted.packages: "*"
      value:
        spring.kafka.consumer.value-deserializer:
          class: org.springframework.kafka.support.serializer.JsonDeserializer
          target: com.dualsoft.banking.events.domain.account.AccountEvent
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.web: debug

clients:
  transaction:
    url: http://localhost:8081



